name: Deployment
on:
  push:
    branches: [main]
  schedule:
  - cron: "0 0 * * 2"

jobs:
  setops-deployment:
    uses: setopsco/github-actions/.github/workflows/build-and-deployment-workflow.yml@v2
    with:
      setops-organization: zweitag
      setops-stages: nodejs
      setops-apps: web
      setops-project: samples
    secrets:
      setops-username: ${{ secrets.SETOPS_USER }}
      setops-password: ${{ secrets.SETOPS_PASSWORD }}
